dist: trusty
group: beta
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_install:
- if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild --update-binary && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi
deploy:
  skip_cleanup: true
  provider: npm
  email: npm@collaborne.com
  api_key:
    secure: "CGFP+6B5RzLS99I1aIqdVVLdig+eeouSBYWcCCaqES5Neanncc9CagBTvV6dI3ovX8UEu1AZzw+EyDm7EdVC8i/3xJYlIHWGggt6WzrgTVqvKnTE6etPYhpW+lkuwvfPFbXnzpA9vJpn/zgO83gq7k9fHrGpG0WdtXGa4yqVHX9VU+kjGFawNqd64mloyUgu6tkonBtUscBWfpbuAKMv3bUnV3/Zcot4aqDaF+Uwa/8RFzmkl/1Ag1wn7PPLQiq14pettxeOuLgkn+puFLdEUbo/w7A5n2XiB75SGLebxkrCJJHgQlL2+U/ntVPY80Zt4GmCySJQ2xn3I9lXQRBMoG9pv5d2l/yNpf9tZU7YxKwRj0YlqhbV1+Q7Z2PdD46DAevgrEC5SqGU6Tbm5BwVANy4ei5TE4BObuUR9pMPctmDGkdG7L3iaxKefDm6bvuBPAGX4oUa6Weq7HK/ia2TB+R5kMVWi56Xz2Cb9a9oFt+dPHoZESWBL9KNSX8r0oG/GJRyx2vUNImP5QUAIBItlahqaR15Job5lL9bXVP7dvpNUGcPiWXLJhX/a/8PULgPphfkELcce1GrQwv0kjcd4kTgM0ZSRQDeKnXOsZKRKwjTTercCpRMyH/wMnO4hxogv4OlPH2JPeY6q08BaEaJnoTkrCQwRL/kEMxRYc/AloM="
  on:
    tags: true
    condition: $(node -e 'console.log("v" + require("./package.json").version)') = ${TRAVIS_TAG}
