dist: trusty
group: beta
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_install:
- if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild --update-binary && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi
deploy:
  skip_cleanup: true
  provider: npm
  email: npm@collaborne.com
  api_key:
    secure: "FSFQCPZO3A4BDBF1ZqMD+xsb/ldWd4/thqKXr+fK5czoyk4hXoXvWWm8ltPffS9NEgq1tU2He9P13otYqd3ZRldaBuxShD8cYeg8BZZsjpAQRS1L+pTXGSoukHEq9webU7oVa5yeQpFwShbwbXJ1jdWH6h3jTbpeoH/W4v/URsxPSvclRhLwSUrvppkgcxgf0/8zTR+/GEdI6VEDvd6sDxjf6rcI/QUfeeEuqpwWj7Q/LC/iwAHDLOTG4zz+ej1eV1vyDDUyZoaYroz2VdxJzsAoOvXdXiSwazZqjkaPhb5MG/UjLiUf+tTG0rMlO+MSmJ00+2kmRwHY2b20gWX+qDTYluImoCXbe7WbAuft1SFbq40XbbVHF3oAqr14HUJOpyeyK2YZ8YNWqti31AD1/GiH2pjmQz38oiHkR+NYvt+JeRIWEekRJgfgOcODIEPFqpW2XoPOB0i/+ZokU1QPVG1nDC1lNJeBSaJUlUnSz0jL9ZVRSUMIQiJX/OmNmdATP3CiFRL+gHIggqrZjA99QHngtLNwS9F35GfC7dBJr2k4zsEckX9mgPt4Ki+zzmdG08E7FElngLcf4nHzY9nu/NwJRNj2xlkzyHdDlr5ZzOn6Up6joKVUxhQcsXR503busCYT8Vq+OabecV9UmDTsxysALp/7b4dhJNaq6xvVonQ="
  on:
    tags: true
    condition: $(node -e 'console.log("v" + require("./package.json").version)') = ${TRAVIS_TAG}
